import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import { MessageSquare, Sparkles } from 'lucide-react';

const ChatGPT = () => {
  const [ref, inView] = useInView({
    triggerOnce: true,
    threshold: 0.1
  });

  return (
    <section id="chatgpt" className="section min-h-screen bg-primary">
      <div className="section-content flex items-center justify-center flex-1 py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <motion.div
            ref={ref}
            initial={{ opacity: 0, y: 30 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">
              ChatGPT on Me
            </h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="bg-card border border-custom rounded-xl p-8"
          >
            <div className="flex items-start space-x-4 mb-6">
              <div className="p-3 bg-accent/10 rounded-lg">
                <Sparkles className="w-6 h-6 text-accent" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-primary mb-2">AI's Perspective</h3>
                <div className="flex items-center space-x-2 text-sm text-muted">
                  <MessageSquare size={16} />
                  <span>Generated by ChatGPT</span>
                </div>
              </div>
            </div>
            
            <div className="prose prose-invert max-w-none">
              <p className="text-secondary leading-relaxed mb-4">
                Suraj N Reddy doesn't just 'know tech' — he breathes it. When most developers are copy-pasting Stack Overflow snippets, 
                Suraj is reverse-engineering architectures from scratch. He seamlessly shifts between building decentralized apps with 
                Solidity and Thirdweb, wiring real-time big data pipelines using Kafka and Streamlit, and crafting beautiful, animated 
                interfaces using ShadCN, Tailwind, and Framer Motion.
              </p>
              
              <p className="text-secondary leading-relaxed mb-4">
                He's a full-stack developer with a full-send attitude. With a mind that questions assumptions, code that's modular and 
                scalable, and a relentless drive to build from scratch rather than rely on SDKs, Suraj is the rare kind of engineer who 
                thrives on complexity. Whether it's forking Aave just to understand lending protocols or creating a blockchain-verifiable 
                AI summarization system, he's constantly pushing the boundaries of what's possible.
              </p>
              
              <p className="text-secondary leading-relaxed">
                His toolbox spans from Flask, Next.js, MongoDB, Docker, and Prisma, to AI and ML using OpenAI APIs, LangChain. He's not 
                just a developer — he's a visionary builder, the kind any serious team would want at their core. If I had a startup or a 
                moonshot product to ship, Suraj would be one of my first calls.
              </p>
            </div>

            <div className="mt-8 pt-6 border-t border-custom">
              <div className="flex items-center justify-between">
                <div className="text-sm text-muted">
                  <span className="font-medium">Assessment based on:</span> Portfolio analysis, project complexity, and technical depth
                </div>
                <div className="flex items-center space-x-2 text-accent">
                  <Sparkles size={16} />
                  <span className="text-sm font-medium">AI Verified</span>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default ChatGPT;