import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import { MessageSquare, Sparkles } from 'lucide-react';

const ChatGPT = () => {
  const [ref, inView] = useInView({
    triggerOnce: true,
    threshold: 0.1
  });

  return (
    <section id="chatgpt" className="section min-h-screen bg-primary">
      <div className="section-content flex items-center justify-center flex-1 py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6">
          <motion.div
            ref={ref}
            initial={{ opacity: 0, y: 30 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-primary mb-4">
              ChatGPT on Me
            </h2>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="bg-card border border-custom rounded-xl p-8"
          >
            <div className="flex items-start space-x-4 mb-6">
              <div className="p-3 bg-accent/10 rounded-lg">
                <Sparkles className="w-6 h-6 text-accent" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-primary mb-2">AI's Perspective</h3>
                <div className="flex items-center space-x-2 text-sm text-muted">
                  <MessageSquare size={16} />
                  <span>Generated by ChatGPT</span>
                </div>
              </div>
            </div>
            
            <div className="prose prose-invert max-w-none">
              <p className="text-secondary leading-relaxed mb-4">
                Suraj N Reddy is not your average developer — he's a systems thinker, product builder, and tech explorer who's redefining what it means to learn by doing. Currently pursuing Information Science and Engineering at BMS College of Engineering, Suraj has consistently stood out for building real-world projects that are not only functional but also impactful.
              </p>
              
              <p className="text-secondary leading-relaxed mb-4">
                He's the mind behind SwasthyaAI, an award-winning AI health assistant for underserved communities, and is actively developing an ML-based vehicle analytics system that tracks real-time traffic data using computer vision. While many developers stop at implementation, Suraj digs deeper — understanding architecture, optimizing patterns, and thinking end-to-end.
              </p>
              
              <p className="text-secondary leading-relaxed mb-4">
                Whether he's forking protocols to learn how they tick, designing pixel-perfect UIs with ShadCN and Tailwind, or crafting intelligent agents using LangChain, OpenAI, and Gemini APIs, Suraj brings a full-stack perspective with a future-focused mindset. He experiments fearlessly across technologies like Next.js, Flask, MongoDB, Prisma, Firebase, and Supabase, tying it all together through scalable, modular systems.
              </p>
              
              <p className="text-secondary leading-relaxed">
                But beyond the code, what sets Suraj apart is his drive to build from scratch, learn obsessively, and deliver meaningfully. He's a builder at heart, driven by curiosity and sharpened by community. From contributing to open-source to winning hackathons, he embodies the spirit of innovation and iteration. If you're looking for someone who doesn't just follow trends but shapes them — someone who builds with purpose and precision — Suraj N Reddy belongs at the core of that journey.
              </p>
            </div>

            <div className="mt-8 pt-6 border-t border-custom">
              <div className="flex items-center justify-between">
                <div className="text-sm text-muted">
                  <span className="font-medium">Assessment based on:</span> Portfolio analysis, project complexity, and technical depth
                </div>
                <div className="flex items-center space-x-2 text-accent">
                  <Sparkles size={16} />
                  <span className="text-sm font-medium">AI Verified</span>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default ChatGPT;